export const ActionType = {
  SORT_OFFERS: `SORT_OFFERS`,
  HIGHLIGHT_MARKER: `HIGHLIGHT_MARKER`,
  // ot
  LOAD_OFFERS: `LOAD_OFFERS`,
  LOAD_FAVORITE_OFFERS: `LOAD_FAVORITE_OFFERS`,
  CHANGE_CITY: `CHANGE_CITY`,
  CHANGE_FAVORITE_CITY: `CHANGE_FAVORITE_CITY`,
  GET_ERROR: `GET_ERROR`
};

export const NameSpace = {
  OFFERS: `OFFERS`,
  SORT: `SORT`,
  REVIEW: `REVIEW`,
  USER: `USER`
};
